module.exports = {
  extends: ["stylelint-config-recommended", "stylelint-config-prettier"],
  plugins: ["stylelint-prettier"],
  rules: {
    "alpha-value-notation": null,
    "at-rule-no-vendor-prefix": null,
    "color-function-notation": null,
    "color-hex-length": "long",
    "color-hex-length": null,
    "custom-property-empty-line-before": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-colon-newline-after": null,
    "font-family-name-quotes": "always-where-recommended",
    "hue-degree-notation": null,
    indentation: [2, { baseIndentLevel: 1 }],
    "prettier/prettier": true,
    "keyframes-name-pattern": null,
    "length-zero-no-unit": null,
    "max-line-length": null,
    "no-descending-specificity": null,
    "no-empty-source": null,
    "no-invalid-position-at-import-rule": null,
    "number-max-precision": null,
    "property-no-unknown": null,
    "property-no-vendor-prefix": null,
    "scss/at-rule-conditional-no-parentheses": null,
    "selector-attribute-quotes": "always",
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-list-comma-newline-after": null,
    "selector-max-id": null,
    "selector-no-vendor-prefix": null,
    "selector-pseudo-element-colon-notation": "single",
    "string-quotes": "single",
    "value-keyword-case": null,
    "value-list-comma-newline-after": null,
    "value-list-max-empty-lines": 0,
    "value-no-vendor-prefix": null,
  },
  overrides: [
    {
      files: ["**/*.scss"],
      customSyntax: "postcss-scss",
      extends: ["stylelint-config-recommended-scss", "stylelint-config-prettier-scss"],
    },
    {
      files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
      customSyntax: "postcss-jsx",
      extends: [
        "stylelint-config-recommended-scss",
        "stylelint-config-prettier-scss",
        "stylelint-config-styled-components",
      ],
    },
  ],
};
