module.exports = {
  extends: [
    "stylelint-config-standard",
    "stylelint-config-standard-scss",
    "stylelint-config-prettier",
    "stylelint-config-rational-order",
  ],
  overrides: [
    {
      files: ["**/*.scss"],
      extends: ["stylelint-config-standard-scss", "stylelint-config-prettier", "stylelint-config-rational-order"],
    },
    {
      files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
      extends: [
        "stylelint-config-recommended",
        "stylelint-config-prettier",
        "stylelint-config-rational-order",
        "stylelint-config-styled-components",
      ],
      customSyntax: "postcss-jsx",
    },
  ],
  rules: {
    "alpha-value-notation": null,
    "at-rule-no-vendor-prefix": null,
    "color-function-notation": null,
    "color-hex-length": "long",
    "color-hex-length": null,
    "custom-property-empty-line-before": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-colon-newline-after": null,
    "font-family-name-quotes": "always-where-recommended",
    "hue-degree-notation": null,
    indentation: 2,
    "keyframes-name-pattern": null,
    "length-zero-no-unit": null,
    "max-line-length": null,
    "no-descending-specificity": null,
    "no-empty-source": null,
    "no-invalid-position-at-import-rule": null,
    "number-max-precision": null,
    "prettier/prettier": true,
    "property-no-unknown": null,
    "property-no-vendor-prefix": null,
    "scss/at-rule-conditional-no-parentheses": null,
    "scss/double-slash-comment-empty-line-before": null,
    "selector-attribute-quotes": "always",
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "selector-list-comma-newline-after": null,
    "selector-max-id": null,
    "selector-no-vendor-prefix": null,
    "selector-pseudo-element-colon-notation": "single",
    "string-quotes": "single",
    "value-keyword-case": null,
    "value-list-comma-newline-after": null,
    "value-list-max-empty-lines": 0,
    "value-no-vendor-prefix": null,
  },
};
